name: app_croissant
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.2
  get: 4.6.6
  dio: 5.4.0
  device_info_plus: 9.1.2
  socket_io_client: 2.0.3+1
  connectivity_plus: 5.0.2
  flutter_background_service: 5.0.5
  flutter_local_notifications: 16.3.2
  get_storage: 2.1.1
  flutter_secure_storage: 9.0.0
  responsive_sizer: 3.3.0+1
  google_fonts: 6.1.0
  lottie: 3.1.0
  rive: 0.12.4
  permission_handler: 11.3.1
  url_launcher: 6.2.5
  sqflite: 2.3.3
  location: 6.0.1
  just_audio: 0.9.37
  toggle_switch: 2.3.0
  auto_size_text: 3.0.0
  flutter_slidable: 3.1.0
  animated_text_kit: 4.2.2
  network_info_plus: 5.0.3
  animate_do: 3.3.4
  animated_toggle_switch: 0.8.2
  animated_splash_screen: 1.3.0
  image_picker: 1.1.0
  local_auth: 2.2.0
  video_player: 2.8.6
  path_provider: 2.1.3
  loading_animation_widget: 1.2.1
  flutter_launcher_icons: 0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logoApp.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: 2.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/CAPTCHA/
    - assets/icons/
    - assets/sticker/
    - assets/lottie/
    - assets/wallpaper/


